name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome to our community! Thank you for opening your first issue. Please provide details about the problem or suggestion you have, and our team will assist you promptly. Be sure to check our contributing guidelines!"
        pr-message: "🎉 Congratulations on your first pull request! We appreciate your contribution. Please make sure your changes align with our contributing guidelines, and our team will review and merge them as soon as possible. If you have any questions, feel free to ask!"
