name: Run Python black code formatter

on:
  push:
    branches:
      - main

jobs:
  run-black-formatter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python black code formatter
      uses: DataDog/action-py-black-formatter@v2.5
